### ISSUE TITLE
Jade template not being displayed/converted to HTML in electron renderer window.

### ISSUE THREAD

**Issue by smilerdude** [yan-foto/electron-jade#11]
Hi,

I've just installed electron-jade to my test electron project.  Following the instructions on the npm project page.

When I launch my test Electron app, the terminal window tells me that "Jade interceptor registered successfully" but when the Renderer Window launches, there is no HTML code at all appearing in the window.  Using the Dev Tools, there is no HTML markup apart from empty nested tags

`<html>`
    `<head>``</head>`
    `<body>``</body>`
`</html>`
 
There's no page title, no text, not tag attributes have been created in the Dom window according to the DevTools.

It's possible that I've messed something up in the configuration and install process but I'm not sure where to begin.

My main.js file looks like this:
````javascript
 'use strict';

var app = require("app");
var locals = {/* ...*/};
var j = require("electron-jade")({pretty: true}, locals);
var browserWindow = require("browser-window");

var mainWindow = null;

app.on('window-all-closed', function() {
    if (process.platform != 'darwin') {
        app.quit();
    }
});

app.on('ready', function() {
    mainWindow = new browserWindow({width: 800, height: 600, 'dark-theme': true});

    mainWindow.loadURL('jade://' + __dirname + '/index.jade');

    mainWindow.openDevTools();
    mainWindow.on('close', function() {
        mainWindow = null;
    });
});
`````
My index.jade from the main page at http://jade-lang.com/ file looks like this:

````html
doctype html
html(lang="en")
  head
    title= pageTitle
    script(type='text/javascript').
      if (foo) {
         bar(1 + 5)
      }
  body
    h1 Jade - node template engine
    #container.col
      if youAreUsingJade
        p You are amazing
      else
        p Get on it!
      p.
        Jade is a terse and simple
        templating language with a
        strong focus on performance
        and powerful features.
````

My package.json file details:

````json
  "devDependencies": {
    "electron-jade": "^1.3.0",
    "electron-prebuilt": "^0.36.1",
    "electron-rebuild": "^1.0.2",
    "jade": "^1.11.0"
  }
````
I'm using Node.js version 5.3.0 on Linux Mint 17.2.

If there's other information you require let me know and I'll get it to you.

**Comment by yan-foto** [comment]
Sorry but I cannot manage to answer questions regarding debugging. If you have found out a bug please report it using the package version and electron version here. For other questions please consult [stackoverflow](https://stackoverflow.com/).

**Comment by macharborguy** [comment]
I had the EXACT same issue, but discovered the reason.  Make sure that the URL you pass to...

```javascript
mainWindow.loadUrl('file://' + __dirname + '/index.jade');
```

...does NOT have any spaces in it.  Either remove any spaces in the directories themselves, or pre-format the URL so the spaces are escaped.

so if the resulting url is...

```
file://Some/Path/To The/File.jade
```

you need to escape the space in 'To The', or just remove the space in that directory name all together

**Comment by yan-foto** [comment]
@macharborguy good point! I am closing this issue then :+1:
