### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by rSafari** [yan-foto/electron-jade#4]
when im loading the jade template like the sample you provided , i get this error.
how can i solve this ?

![error](https://cloud.githubusercontent.com/assets/1060150/9423811/2053a334-48e9-11e5-97b1-f01e10505039.jpg)

**Comment by yan-foto** [comment]
This error usually means that the resource does not exist on the path given. Use an older version (i.e. `npm install electron-jade@0.2.0`) and try the following:

```js
mainWindow.loadUrl('jade://' + __dirname + '/index.jade');
```

(note `jade://` instead of `file://`). The older versions use another approach that might solve your problem. It would also help me to target any bugs.

**Comment by rSafari** [comment]
yea , thank you .
installing 0.2.0 version fixed the problem. also the jade:// thing is important too .

**Comment by yan-foto** [comment]
No it's not in the new version. I just found out that electron has updated the `protocol` API. I am updating to the newest version and will publish ASAP.

**Comment by rSafari** [comment]
another problem is , its trying to load everything with jade:// protocol !!
![err2](https://cloud.githubusercontent.com/assets/1060150/9423956/0d366e8e-48ef-11e5-9f0f-f29c7af626df.jpg)

**Comment by yan-foto** [comment]
Yep, the newest version of electron broke everything :confused:

**Comment by yan-foto** [comment]
I published a new version on npm which is compatible to electron's new [protocol API](https://github.com/atom/electron/blob/master/docs/api/protocol.md). give it a try and let me know if it works :wink:

**Comment by rSafari** [comment]
i updated the package , but i'm not sure whats happening in here really ...

here is my jade file

doctype html
html(lang="en")
  head
    title= "Faratech Theme Maker v0.1"
    script(src='../assets/js/jquery.min.js')
    script(src='../filereader.js')
    script(src='../assets/js/system.js')
  body
    div.welcome
        img(src="../assets/img/faratech.png")
    div.footer-commands
        a.btn.btn-success Next
            i.fa.fa-angle-right

look at those error ... what is really happening !
            
![err3](https://cloud.githubusercontent.com/assets/1060150/9424147/7485bf5c-48f6-11e5-899e-ce8062976d6f.jpg)

**Comment by jvhoven** [comment]
@yan-foto Good job on updating it so quickly man!

I'm having the same error as @rSafari, all my static calls are now replace with jade calls sadly..
If you don't mind me asking, where did you find the updated docs? Github still has the old documentation about protocol.

**Comment by yan-foto** [comment]
Those errors seems to be jade errors. I cannot really know why you get them.

**Comment by yan-foto** [comment]
@rSafari @jvhoven version `1.2.0` is now compatible with the new `protocol` API and the bug with binary files has been solved.

**Comment by yan-foto** [comment]
@rSafari both of your errors are Javascript related, I see no reason that they might be related to this module.

**Comment by rSafari** [comment]
look at the files address, it starts with jade://
why exactly ?

**Comment by yan-foto** [comment]
@rSafari because you still are using the old version with `jade://` protocol. use the new one and use `file://` scheme instead.

**Comment by rSafari** [comment]
i'm using neutron of yours . but after updating to new version of electron-jade i get this error :

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: protocol.interceptBufferProtocol is not a function
    at EventEmitter.<anonymous> (D:\Projects\Next\dist\node_modules\electron-jade\index.js:13:14)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

**Comment by yan-foto** [comment]
you have to use latest version of `electron-prebuilt`. If its a neutron issue, open one over there. But It isn't! either you are using an old version of `electron` to run the neutron generated package or you just need to update `electron-prebuilt` to the latest electron version (released [2 days ago](https://github.com/atom/electron/releases/tag/v0.31.0)):

```
npm un electron-prebuilt
npm i electron-prebuilt
```

**Comment by rSafari** [comment]
this might be ugly but i think this project have some serious problems !
in line 14 of index.js you add var file = request.url.substr(7);
and that make serious issues to the whole system. i couldn't use this project at last. i updated everything , even updated electron-prebuilt. there is no problem loading html files. but lot of problems on jade files. i fix someplace , other place broke. 
i don't know if you even care for this because this is a open source project and no one pay you for this but you should respect your self :)

**Comment by yan-foto** [comment]
You cannot contribute your lack of JS knowledge to 'serious problems' within the project. You don't give exact errors so no one could reproduce the unspecified errors you are getting.

You should most definitely read [contributor covenant](http://contributor-covenant.org/version/1/2/0/) and avoid any offensive language or getting personal.
