### ISSUE TITLE
Problem with parameterized paths

### ISSUE THREAD

**Issue by jvhoven** [yan-foto/electron-jade#8]
The path package from nodejs is in the fault this time, some major libraries like the one I'm using, material design icons, use parameterized requests for example:

```
/fonts/materialdesignicons-webfont.eot?#iefix&v=1.1.70
```

Which makes this bit of code return .70 instead of the actual extension, which then returns the wrong mimetype for the file.

```
var ext = path.extname(file);
```

Sorry to bother you once again!
Too afraid to send you a pull request thinking the solution I made is inferior to yours :(

**Comment by yan-foto** [comment]
The problem in this case is that you are trying to mix `HTTP` scheme with `file` scheme. According to the [RFC 1738](https://tools.ietf.org/html/rfc1738) an HTTP scheme looks like the following:

```
http://<host>:<port>/<path>?<searchpart>
``` 
whereas a file scheme is like:
```
file://<host>/<path>
```
As you can see there are no `searchpart`s in file scheme as it doesn't make sense at all!

**Comment by jvhoven** [comment]
Yeah except Im not trying that. Im just trying to load this libraryhttps://github.com/Templarian/MaterialDesign-Webfont/blob/master/css/materialdesignicons.css

**Comment by yan-foto** [comment]
It is being assumed that files are served over a server through an HTTP server. that is why its not working. See [this line](https://github.com/Templarian/MaterialDesign-Webfont/blob/master/css/materialdesignicons.css#L4)

**Comment by yan-foto** [comment]
The logic is now more intelligent!

**Comment by jvhoven** [comment]
Had to double check, but the default file protocol does support this, so thank you for updating!

**Comment by yan-foto** [comment]
I would say it ignores it instead of supporting it.
